CombineConflictsWithPlateID.GCL= function(files){
######################################################################################################################################################################################
################################### 	THIS FUNCTION REQUIRES THE PACKAGE "xlsx"  ###########################################################################################################
#
#   This function is for combining QC conflict reports and adding a column of PLATE_IDs associated with each individual conflict.
#
#   For this to work you must have "*.gcl" objects and "ProjectSillys" created by ReadProjectLOKI2R.GCL 
#  
#   ProjectSillys is a vector of Silly codes generated by ReadProjectLOKI2R.GCL

#    "files" A vector of.csv files in "dir" that you want to combine with the extension.
#    Example: files=c("CM31 QC 01 Import Results.csv","CM31 QC 02 Import Results.csv","CM31 QC Plate3 Imports.csv")
#    
#    source("V:/WORK/Andy/R/CombineConflictsWithPlateID.GCL/testobjects.txt")
#  Written by Andy Barclay 9/28/12
#  Modified by Kyle Shedd 10/16/15 attributes$plateID -> attributes$PLATE_ID (lines 47 & 64)
#  Modified by Kyle Shedd 02/23/16 to accomodate new LOKI QC Concordance Report
################################################################################################################

require("xlsx")

N <- length(files)
data = NULL

for(i in seq(N)){
  NextFile <- read.csv(files[i], header = TRUE)[,-1]
  end <- dim(NextFile)[1]  # added this
  data <- rbind(data, NextFile[1:end, ])
}

data <- with(data, data.frame(Silly.Code = Silly.Code, Fish.ID = Fish.ID, Silly.Source = paste(Silly.Code, "_", Fish.ID, sep = ''), Locus = Locus, Allele.1 = File.Allele.1, Allele.2 = File.Allele.2, DB.Allele.1 = DB.Allele.1, DB.Allele.2 = DB.Allele.2, Conflict = Concordance, Type = Concordance.Type, PlateID = rep(NA, length(Silly.Code))))

data <- merge(x = data.frame(Silly.Code = ProjectSillys), y = data, by.x = "Silly.Code", by.y = "Silly.Code")

if(length(ProjectSillys) > 1) { 
  IDs = sapply(ProjectSillys, function(silly) {
    my.gcl = paste(silly,".gcl",sep='');
    SillySource = as.vector(get(my.gcl)$attributes$SillySource);
    IDs = get(my.gcl)$attributes$PLATE_ID;
    IDmat <- cbind(SillySource, as.vector(IDs));
    return(IDmat)}, USE.NAMES = TRUE, simplify = FALSE)
  
  PlateID = Reduce(f = rbind, x = IDs)
} 

if(length(ProjectSillys) == 1) {   
  my.gcl = paste(ProjectSillys, ".gcl", sep = '')
  SillySource = as.vector(get(my.gcl)$attributes$SillySource)
  IDs = get(my.gcl)$attributes$PLATE_ID
  PlateID <- cbind(SillySource, as.vector(IDs))
}

dimnames(PlateID)[[2]] = c("SillySource","IDs")  

confSillySource <- as.vector(data[, "Silly.Source"])  

for(ind in confSillySource){
  
  if(length(PlateID[, "IDs"][PlateID[, "SillySource"] == ind]) == 0) {next()}
  
  data[data[, "Silly.Source"] == ind, "PlateID"] = PlateID[, "IDs"][PlateID[, "SillySource"] == ind]
}

write.xlsx(data, file = "Conflict Reports/CombinedConflictsWithPlateID.xlsx")

assign(x = "CombinedConflicts", value = data, pos = 1)
}

             
      
     
